### PR TITLE
Add back abstractFormatOps method

### PR DESCRIPTION
**Pull request by nicksovich**
@jeffmay @rh-nalitkin please review

### CODE REVIEW

**Comment by jeffmay** [comment]
Feel free to use this snapshot for testing, but I all changes to this repo should go to the community version first, then merge to rally.

**Comment by rh-nalitkin** [comment]
calvinball snapshot -> https://github.com/AudaxHealthInc/calvinball/pull/241

**Comment by rh-nalitkin** [comment]
going to run RCU

**Comment by shinjik** [comment]
@rh-nalitkin lgtm, run it! (trollfish)

**Comment by jeffmay** [comment]
Closing in favor of https://github.com/jeffmay/play-json-ops/pull/20

**Pull request closed without merging**
